🐛 fix(release): evita a validação com commitizen se o commit for para release

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -1,8 +1,17 @@
+# This hook is called by "git commit" and can be used to modify the message before it is committed. If the exit status is non-zero, then the commit is aborted.
+# If message is empty, execute cz
+if [ -z "$2" ]; then
+  exec < /dev/tty && npx cz --hook || true
+  exit 0
+fi
+# If message is a release commit, skip validation
 message=$1
 trailer=$(git interpret-trailers --parse ${message} | grep '^author:')
 echo "trailer: $trailer"
 if [ "$trailer" = 'author: release' ]; then
   echo "Skipping commit message validation because it's a release commit"
   exit 0
+else
+  exec < /dev/tty && npx cz --hook || true
+  exit 0
 fi
-exec < /dev/tty && npx cz --hook || true
